/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface ArbRetryableTxInterface extends utils.Interface {
  functions: {
    "cancel(bytes32)": FunctionFragment;
    "getBeneficiary(bytes32)": FunctionFragment;
    "getKeepalivePrice(bytes32)": FunctionFragment;
    "getLifetime()": FunctionFragment;
    "getSubmissionPrice(uint256)": FunctionFragment;
    "getTimeout(bytes32)": FunctionFragment;
    "keepalive(bytes32)": FunctionFragment;
    "redeem(bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "cancel"
      | "getBeneficiary"
      | "getKeepalivePrice"
      | "getLifetime"
      | "getSubmissionPrice"
      | "getTimeout"
      | "keepalive"
      | "redeem"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "cancel",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getBeneficiary",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getKeepalivePrice",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getLifetime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSubmissionPrice",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTimeout",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "keepalive",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getKeepalivePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLifetime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubmissionPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTimeout", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "keepalive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;

  events: {
    "Canceled(bytes32)": EventFragment;
    "LifetimeExtended(bytes32,uint256)": EventFragment;
    "Redeemed(bytes32)": EventFragment;
    "TicketCreated(bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Canceled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LifetimeExtended"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Redeemed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TicketCreated"): EventFragment;
}

export interface CanceledEventObject {
  ticketId: string;
}
export type CanceledEvent = TypedEvent<[string], CanceledEventObject>;

export type CanceledEventFilter = TypedEventFilter<CanceledEvent>;

export interface LifetimeExtendedEventObject {
  ticketId: string;
  newTimeout: BigNumber;
}
export type LifetimeExtendedEvent = TypedEvent<
  [string, BigNumber],
  LifetimeExtendedEventObject
>;

export type LifetimeExtendedEventFilter =
  TypedEventFilter<LifetimeExtendedEvent>;

export interface RedeemedEventObject {
  ticketId: string;
}
export type RedeemedEvent = TypedEvent<[string], RedeemedEventObject>;

export type RedeemedEventFilter = TypedEventFilter<RedeemedEvent>;

export interface TicketCreatedEventObject {
  ticketId: string;
}
export type TicketCreatedEvent = TypedEvent<[string], TicketCreatedEventObject>;

export type TicketCreatedEventFilter = TypedEventFilter<TicketCreatedEvent>;

export interface ArbRetryableTx extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ArbRetryableTxInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cancel(
      ticketId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getBeneficiary(
      ticketId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getKeepalivePrice(
      ticketId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getLifetime(overrides?: CallOverrides): Promise<[BigNumber]>;

    getSubmissionPrice(
      calldataSize: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getTimeout(
      ticketId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    keepalive(
      ticketId: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    redeem(
      txId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  cancel(
    ticketId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getBeneficiary(
    ticketId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  getKeepalivePrice(
    ticketId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  getLifetime(overrides?: CallOverrides): Promise<BigNumber>;

  getSubmissionPrice(
    calldataSize: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  getTimeout(
    ticketId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  keepalive(
    ticketId: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  redeem(
    txId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    cancel(
      ticketId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    getBeneficiary(
      ticketId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    getKeepalivePrice(
      ticketId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getLifetime(overrides?: CallOverrides): Promise<BigNumber>;

    getSubmissionPrice(
      calldataSize: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getTimeout(
      ticketId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    keepalive(
      ticketId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    redeem(
      txId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Canceled(bytes32)"(
      ticketId?: PromiseOrValue<BytesLike> | null
    ): CanceledEventFilter;
    Canceled(ticketId?: PromiseOrValue<BytesLike> | null): CanceledEventFilter;

    "LifetimeExtended(bytes32,uint256)"(
      ticketId?: PromiseOrValue<BytesLike> | null,
      newTimeout?: null
    ): LifetimeExtendedEventFilter;
    LifetimeExtended(
      ticketId?: PromiseOrValue<BytesLike> | null,
      newTimeout?: null
    ): LifetimeExtendedEventFilter;

    "Redeemed(bytes32)"(
      ticketId?: PromiseOrValue<BytesLike> | null
    ): RedeemedEventFilter;
    Redeemed(ticketId?: PromiseOrValue<BytesLike> | null): RedeemedEventFilter;

    "TicketCreated(bytes32)"(
      ticketId?: PromiseOrValue<BytesLike> | null
    ): TicketCreatedEventFilter;
    TicketCreated(
      ticketId?: PromiseOrValue<BytesLike> | null
    ): TicketCreatedEventFilter;
  };

  estimateGas: {
    cancel(
      ticketId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getBeneficiary(
      ticketId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getKeepalivePrice(
      ticketId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLifetime(overrides?: CallOverrides): Promise<BigNumber>;

    getSubmissionPrice(
      calldataSize: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTimeout(
      ticketId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    keepalive(
      ticketId: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    redeem(
      txId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    cancel(
      ticketId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getBeneficiary(
      ticketId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getKeepalivePrice(
      ticketId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLifetime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSubmissionPrice(
      calldataSize: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTimeout(
      ticketId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    keepalive(
      ticketId: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    redeem(
      txId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
