/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface NodeInterfaceInterface extends utils.Interface {
  functions: {
    "estimateRetryableTicket(address,uint256,address,uint256,address,address,bytes)": FunctionFragment;
    "lookupMessageBatchProof(uint256,uint64)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "estimateRetryableTicket"
      | "lookupMessageBatchProof"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "estimateRetryableTicket",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "lookupMessageBatchProof",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "estimateRetryableTicket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lookupMessageBatchProof",
    data: BytesLike
  ): Result;

  events: {};
}

export interface NodeInterface extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: NodeInterfaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    estimateRetryableTicket(
      sender: PromiseOrValue<string>,
      deposit: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      l2CallValue: PromiseOrValue<BigNumberish>,
      excessFeeRefundAddress: PromiseOrValue<string>,
      callValueRefundAddress: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    lookupMessageBatchProof(
      batchNum: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        string[],
        BigNumber,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        string
      ] & {
        proof: string[];
        path: BigNumber;
        l2Sender: string;
        l1Dest: string;
        l2Block: BigNumber;
        l1Block: BigNumber;
        timestamp: BigNumber;
        amount: BigNumber;
        calldataForL1: string;
      }
    >;
  };

  estimateRetryableTicket(
    sender: PromiseOrValue<string>,
    deposit: PromiseOrValue<BigNumberish>,
    to: PromiseOrValue<string>,
    l2CallValue: PromiseOrValue<BigNumberish>,
    excessFeeRefundAddress: PromiseOrValue<string>,
    callValueRefundAddress: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<void>;

  lookupMessageBatchProof(
    batchNum: PromiseOrValue<BigNumberish>,
    index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      string[],
      BigNumber,
      string,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      string
    ] & {
      proof: string[];
      path: BigNumber;
      l2Sender: string;
      l1Dest: string;
      l2Block: BigNumber;
      l1Block: BigNumber;
      timestamp: BigNumber;
      amount: BigNumber;
      calldataForL1: string;
    }
  >;

  callStatic: {
    estimateRetryableTicket(
      sender: PromiseOrValue<string>,
      deposit: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      l2CallValue: PromiseOrValue<BigNumberish>,
      excessFeeRefundAddress: PromiseOrValue<string>,
      callValueRefundAddress: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    lookupMessageBatchProof(
      batchNum: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        string[],
        BigNumber,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        string
      ] & {
        proof: string[];
        path: BigNumber;
        l2Sender: string;
        l1Dest: string;
        l2Block: BigNumber;
        l1Block: BigNumber;
        timestamp: BigNumber;
        amount: BigNumber;
        calldataForL1: string;
      }
    >;
  };

  filters: {};

  estimateGas: {
    estimateRetryableTicket(
      sender: PromiseOrValue<string>,
      deposit: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      l2CallValue: PromiseOrValue<BigNumberish>,
      excessFeeRefundAddress: PromiseOrValue<string>,
      callValueRefundAddress: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lookupMessageBatchProof(
      batchNum: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    estimateRetryableTicket(
      sender: PromiseOrValue<string>,
      deposit: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      l2CallValue: PromiseOrValue<BigNumberish>,
      excessFeeRefundAddress: PromiseOrValue<string>,
      callValueRefundAddress: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lookupMessageBatchProof(
      batchNum: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
