export {
  createControllerStore,
  createStorage,
  deepMerge,
  getMediaSourceType,
  noopStorage,
  parsePlaybackInfo,
  version,
} from "@livepeer/core";
export type {
  AccessControlParams,
  Address,
  AriaText,
  AudioSrc,
  AudioTrackSelector,
  Base64Src,
  ClipLength,
  ClipParams,
  ControlsOptions,
  ControlsState,
  DeviceInformation,
  ElementSize,
  Hash,
  HlsSrc,
  InitialProps,
  MediaControllerCallbackState,
  MediaControllerState,
  MediaControllerStore,
  MediaMetrics,
  MediaSizing,
  Metadata,
  MetricsStatus,
  ObjectFit,
  PlaybackError,
  PlaybackMonitor,
  SingleAudioTrackSelector,
  SingleTrackSelector,
  SingleVideoTrackSelector,
  Src,
  Storage,
  VideoSrc,
  VideoTrackSelector,
  WebRTCSrc,
} from "@livepeer/core";
